# https://docs.github.com/en/packages/managing-github-packages-using-github-actions-workflows/publishing-and-installing-a-package-with-github-actions#publishing-a-package-using-an-action

name: Create and publish a Docker image

on:
  push:
    branches: ['release']

env:
  REGISTRY: ghcr.io
  IMAGE_NAME: ${{ github.repository }}
  MATLAB_RELEASE: r2022b
  MATLAB_ROOT: "/opt/matlab/R2022b"
  FEATURE_TAG: simulink
  ADDITIONAL_TOOLBOXES: "Simulink"


jobs:
  build-and-push-image:
    runs-on: ubuntu-latest
    permissions:
      contents: read
      packages: write

    steps:
      - name: set up envvars
        run: |
          echo "MATLAB_ROOT=/opt/matlab/${MATLAB_RELEASE/#r/R}" >> $GITHUB_ENV

      - name: Checkout repository
        uses: actions/checkout@v3

      - name: Log in to the Container registry
        uses: docker/login-action@65b78e6e13532edd9afa3aa52ac7964289d1a9c1
        with:
          registry: ${{ env.REGISTRY }}
          username: ${{ github.actor }}
          password: ${{ secrets.GITHUB_TOKEN }}

#      - name: Extract metadata (tags, labels) for Docker
#        id: meta
#        uses: docker/metadata-action@9ec57ed1fcdbf14dcef7dfbe97b2010124a938b7
#        with:
#          images: ${{ env.REGISTRY }}/${{ env.IMAGE_NAME }}

      - name: Build Docker image
        uses: docker/build-push-action@f2a1d5e99d037542a71f64918e516c093c6f3fc4
        with:
          context: .
          load: true
          tags: ${{ env.IMAGE_NAME}}:${{ env.MATLAB_RELEASE }}-${{ env.FEATURE_TAG }}
          build-args: |
            MATLAB_RELEASE=${{ env.MATLAB_RELEASE }}
            MATLAB_ROOT=${{ env.MATLAB_ROOT }}
            ADDITIONAL_TOOLBOXES=${{ env.ADDITIONAL_TOOLBOXES }}
#          tags: ${{ steps.meta.outputs.tags }}
#          labels: ${{ steps.meta.outputs.labels }}

      - name: Test Docker image
        run: |
          docker run --rm ${{ env.IMAGE_NAME }}:${{ env.MATLAB_RELEASE }}-${{ env.FEATURE_TAG }} /bin/bash -c "test -d ${{ env.MATLAB_ROOT }}/simulink"

      - name: Push Docker image
        uses: docker/build-push-action@f2a1d5e99d037542a71f64918e516c093c6f3fc4
        with:
          context: .
          push: true
          platforms: linux/amd64
          tags: ${{ env.IMAGE_NAME}}:${{ env.MATLAB_RELEASE }}-${{ env.FEATURE_TAG }}
